### ISSUE TITLE
[Bug]: Timestamp problem

### ISSUE THREAD

**Issue by sascha-hendel** [fabianwennink/IconCaptcha-PHP#41]
### Bug report requirements

- [X] I have confirmed that this is a bug and not a configuration/user error.
- [X] I have searched for existing issues and confirmed that my issue has not been reported before.

### IconCaptcha version

4.0.1 / 4.0.2

### PHP version

8.1

### Browsers affected

Microsoft Edge

### Expectation

You should allow a certain amount of "unexact" time for the test. And if test stills fail, an explaining error message for the user (something like : check your system time!) would be more helpful than the general "something fails" ;) 
 

### Actual behaviour

If client's and server's clock are not perfectly synchronized (and client's clock is just a little more in the future) `Request.php` will deliver `Bad request (400)` because timestamp check (lines 98-110) fails!

### Relevant log information

```shell
---
```

**Comment by fabianwennink** [comment]
Hi! Thank you for your bug report. Coincidentally, I just experienced the same bug while implementing IconCaptcha in a website myself. I'm most likely going to remove this check completely, as it just seems to be too inconsistent from the reports I've received.

**Comment by fabianwennink** [comment]
Hi! This issue has been resolved in version [4.0.3](https://github.com/fabianwennink/IconCaptcha-PHP/releases/tag/4.0.3). The timestamp check has been completely removed in this release.
