### ISSUE TITLE
[Bug]: Division by zero error

### ISSUE THREAD

**Issue by MWA-NASMO** [fabianwennink/IconCaptcha-PHP#43]
### Bug report requirements

- [X] I have confirmed that this is a bug and not a configuration/user error.
- [X] I have searched for existing issues and confirmed that my issue has not been reported before.

### IconCaptcha version

4.0.3

### PHP version

8.1

### Browsers affected

Google Chrome, Mozilla Firefox, Safari

### Expectation

when i go to https://staging-avoventes.cnbnet.fr/ and the click on the "Inscription" button, a modal appears with the iconCaptcha. clicking on the "Verifiez que vous etes humain" show the icons properly, but when you clock on an icon, an error occurs...

### Actual behaviour

The captcha is loading properly but when i select the image, i have that error :
Division by zero {"exception":"[object] (DivisionByZeroError(code: 0): Division by zero at /var/www/cnb-avoventes/vendor/fabianwennink/iconcaptcha/src/Challenge/Challenge.php:365)

The error is there : 
 private function determineClickedIcon(int $clickedXPos, int $clickedYPos, int $captchaWidth, int $iconAmount): int
    {
        // Check if the clicked position is valid.
        if ($clickedXPos < 0 || $clickedXPos > $captchaWidth || $clickedYPos < 0 || $clickedYPos > self::MAX_HEIGHT_OF_CHALLENGE) {
            return -1;
        }
        return (int)ceil($clickedXPos / ($captchaWidth / $iconAmount));   // <--- line 365
    }

### Relevant log information

```shell
I put the same code im my dev server and everything works well (see epimmo.mwa.fr)
```

### Additional information

The error occurs on my PreProd server, these are the appache directive differences :
--- Serveu on wich the iConCaptcha Works : --------------
add_header Strict-Transport-Security “max-age=31536000; includeSubDomains” always;
    add_header X-XSS-Protection “1; mode=block”;
    add_header X-Frame-Options deny always;
    add_header Permissions-Policy “fullscreen=self, geolocation=*“;
    add_header Referrer-Policy no-referrer-when-downgrade;
    add_header X-Content-Type-Options nosniff;

----- Server on wich it does'nt work : ---------
add_header Content-Security-Policy “script-src ‘self’ ‘unsafe-inline’ ‘unsafe-eval’ *.[cookiebot.com](http://cookiebot.com/) *.[sharethis.com](http://sharethis.com/) [maps.googleapis.com](http://maps.googleapis.com/) [www.google.com](http://www.google.com/) [www.google.fr](http://www.google.fr/) [www.gstatic.com](http://www.gstatic.com/) https://stats.avocat.fr/ https://embed.tawk.to/ https://cdn.jsdelivr.net/ *.[jquery.com](http://jquery.com/) *.[cloudflare.com](http://cloudflare.com/) *.[bootstrapcdn.com](http://bootstrapcdn.com/); frame-src ‘self’ [cotisation.cnb.avocat.fr](http://cotisation.cnb.avocat.fr/) [cotisation-staging.adcot.cnbnet.fr](http://cotisation-staging.adcot.cnbnet.fr/) [staging-cotisation.cnbnet.fr](http://staging-cotisation.cnbnet.fr/) [consentcdn.cookiebot.com](http://consentcdn.cookiebot.com/) [www.google.com](http://www.google.com/) https://ws.sharethis.com/; style-src ‘self’ ‘unsafe-inline’ [fonts.gstatic.com](http://fonts.gstatic.com/)  [fonts.googleapis.com](http://fonts.googleapis.com/)  https://ws.sharethis.com/ *.[bootstrapcdn.com](http://bootstrapcdn.com/) https://embed.tawk.to/; frame-ancestors ‘none’“;

**Comment by fabianwennink** [comment]
Hi, what I think is the problem is that the session can't be loaded on your production server. The payload values which are sent to the server in the request are correct, there is nothing strange there. All payload values contain expected values.

The zero value in this case is most likely `$iconAmount`, which is loaded from the session on line 232 of the same file. This might be due to your server settings or your security policies which are set incorrectly or set too strict. Especially since it does work on your development server.

**Comment by fabianwennink** [comment]
Closed due to inactivity
