### ISSUE TITLE
[Bug]:  Responsive issue 

### ISSUE THREAD

**Issue by Maaaleeek** [fabianwennink/IconCaptcha-PHP#44]
### Bug report requirements

- [X] I have confirmed that this is a bug and not a configuration/user error.
- [X] I have searched for existing issues and confirmed that my issue has not been reported before.

### IconCaptcha version

4.0.3

### PHP version

7.4.33

### Browsers affected

Google Chrome

### Expectation

1- Set the browser to mobile mode with a screen width of 320px.
2- Load the page with iconCaptcha.

### Actual behaviour

The content of the canvas is truncated, and we are unable to select the icons.
I thnik that it is necessary to add this attribute **`AbstractImageGenerator::CAPTCHA_IMAGE_SIZE`** in the configuration elements, such as **`iconPath`**. This way, we can adjust the size of the container based on the page padding. In my case the page container in mobile is 250px.

<img width="462" alt="Capture d’écran 2024-02-05 à 12 23 35" src="https://github.com/fabianwennink/IconCaptcha-PHP/assets/117845056/f1173677-b136-492a-838d-f63af20eac74">
<img width="462" alt="Capture d’écran 2024-02-05 à 13 43 25" src="https://github.com/fabianwennink/IconCaptcha-PHP/assets/117845056/6eca97aa-b576-4ba0-ae3d-1b43bd580c13">

**Comment by fabianwennink** [comment]
Hi! Yes, I'm aware that on the very small screen widths - as well as inside small containers - the challenge image will not be displayed correctly. This partially is a bug, but part of it also has to do with it simply being a limitation of how small the image can be generated before it becomes unusable / impossible to select the correct icon.

The challenge image of course should not be cut of as shown in the attached images. This most likely is a bug from the transition between rendering the challenge as an `<img>` and drawing it on a `<canvas>`. I will investigate this and push a fix if I find one.

**Comment by Maaaleeek** [comment]
Hi @fabianwennink, thank you for replay.
Actually, the canvas size is forced to 320px, and the rest is overflow (hidden) from the container.
I have implemented a changement in my projet to use the size of the icon container as a reference if the size is < 320.
I obtained this rendering with the maximum number of icons:, and the correct icon still selectable.
If you wish, I can share my proposed change with you.
<img width="563" alt="Capture d’écran 2024-02-06 à 11 04 34" src="https://github.com/fabianwennink/IconCaptcha-PHP/assets/117845056/e40fc9f9-36f8-4546-a761-4e981fe07f91">

I

**Comment by fabianwennink** [comment]
I've made a small adjustment to the javascript code in the client assets repository. The width and height of the challenge image now renders correctly on smaller screens. The dimensions of the challenge is calculated based on the width of the element. On smaller screens, this means that the image resizes in both width and height to fit the screen. This does mean though that the image also gets smaller in size.

You can find the updated code [here](https://github.com/fabianwennink/IconCaptcha-Widget/blob/4.x/dist/js/iconcaptcha.min.js). Just replace the code in your iconcaptcha.min.js file with this. I will release the version officially later.

**Comment by Maaaleeek** [comment]
After implementing the changes you suggested, the bug has been successfully resolved. Thank you for your assistance.

However, there is one remaining issue: when setting `showCredits` to `false`, the `modal__footer` element is not removed as expected.

<img width="607" alt="Capture d’écran 2024-02-06 à 22 05 58" src="https://github.com/fabianwennink/IconCaptcha-PHP/assets/117845056/cd659259-5d50-4042-91c7-bea99ed934c9">

Additionally, it would be advantageous to have the capability to adjust text , borders, and landing icon colors directly from the initial configuration JS function `IconCaptcha.init`, similar to how `fontFamily` configuration is handled. 

If you agree, I can submit a Feature Request regarding this matter.

**Comment by Maaaleeek** [comment]
However, there is other remaining issue: when setting `showCredits` to `false`, the `modal__footer` element is not removed as expected.

<img width="607" alt="Capture d’écran 2024-02-06 à 22 05 58" src="https://github.com/fabianwennink/IconCaptcha-PHP/assets/117845056/cd659259-5d50-4042-91c7-bea99ed934c9">

Additionally, it would be advantageous to have the capability to adjust text , borders, and landing icon colors directly from the initial configuration JS function `IconCaptcha.init`, similar to how `fontFamily` configuration is handled. 

If you agree, I can submit a Feature Request regarding this matter.

**Comment by Maaaleeek** [comment]
Perfect, I appreciate your support.
